### ISSUE TITLE
start报错

### ISSUE THREAD

**Issue by fanlyze** [xpioneer/koa-graphql-typescript#7]
TSError: ⨯ Unable to compile TypeScript:
src/core/postData/index.ts(30,5): error TS2322: Type 'unknown' is not assignable to type 'object'.

    at createTSError (E:\repository\React\koa-graphql-typescript\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (E:\repository\React\koa-graphql-typescript\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (E:\repository\React\koa-graphql-typescript\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (E:\repository\React\koa-graphql-typescript\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (E:\repository\React\koa-graphql-typescript\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by xpioneer** [comment]
typescript类型检测报错，可能跟版本有关系，已修复。
